---
- name: Copy patroni
  copy:
    src: patroni-2.1.3-1.el7.x86_64.rpm
    dest: /tmp
  tags: install_patrony

- name: Install patroni rpm
  yum:
    name: 
    - /tmp/patroni-2.1.3-1.el7.x86_64.rpm
    - patroni-consul
    disable_gpg_check: yes
    state: present
  tags: install_patrony

- name: Change ownership of a directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: postgres
    group: postgres
    mode: '700'
  loop:
    - /pgsql
    - '{{ path_postgres_data }}'
    - '{{ path_postgres_wal }}'
  tags: chown_dir

- name: Create patroni log directory
  file:
    path: /var/log/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'
  tags: patroni_bin

- name: Template a file to etc/postgresql.yml
  ansible.builtin.template:
    src: postgresql.yml.j2
    dest: /opt/app/patroni/etc/postgresql.yml
    owner: postgres
    group: postgres
  notify: 
    - Start and enabled patroni
  tags: template_patroni
