---
- name: Create vg
  community.general.lvg:
    vg: pg
    pvs: /dev/sdb,/dev/sdc
  tags: create_pg

- name: Create {{ pg_lv1 }}
  community.general.lvol:
    vg: pg
    lv: "{{ pg_lv1 }}"
    size: 100%PVS
    pvs: /dev/sdb
  when: ansible_lvm.lvs.{{ pg_lv1 }} is not defined  
  tags: create_vg

- name: Create {{ pg_lv2 }}
  community.general.lvol:
    vg: pg
    lv: "{{ pg_lv2 }}"
    size: 100%PVS
    pvs: /dev/sdc
  when: ansible_lvm.lvs.{{ pg_lv2 }} is not defined 
  tags: create_vg

- name: Create file system ext4 for {{ pg_lv1 }}
  filesystem:
    fstype: ext4
    dev: /dev/pg/{{ pg_lv1 }}
  tags: create_file_system

- name: Mount {{ pg_lv1 }} to /pgsql/{{ pg_lv1 }}
  mount:
    path: /pgsql/{{ pg_lv1 }}
    src: /dev/pg/{{ pg_lv1 }}
    fstype: ext4
    state: mounted
  tags: create_file_system

- name: Create file system ext4 for {{ pg_lv2 }}
  filesystem:
    fstype: ext4
    dev: /dev/pg/{{ pg_lv2 }}
  tags: create_file_system

- name: Mount {{ pg_lv2 }} to /pgsql/{{ pg_lv2 }}
  mount:
    path: /pgsql/{{ pg_lv2 }}
    src: /dev/pg/{{ pg_lv2 }}
    fstype: ext4
    state: mounted
  tags: create_file_system
  