---
- name: Copy db in /tmp
  copy:
    src: demo-small-20170815.sql
    dest: /tmp
  tags: copy_db

- name: Import db
  ansible.builtin.shell: "psql -f /tmp/demo-small-20170815.sql" 
  become_user: postgres
  tags: copy_db
